name: Build Tweak
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: poomsmart/theos:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & package
        run: |
          export THEOS=/theos
          export THEOS_PACKAGE_SCHEME=rootless
          make package

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
